"""initial_schema

Revision ID: b8cd4982360d
Revises: 
Create Date: 2026-09-17 03:22:19.064406
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8cd4982360d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=7), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.String(length=10), nullable=True),
    sa.Column('period_end', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_by', sa.Integer(), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('closed_reason', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_periods_code'), 'accounting_periods', ['code'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=40), nullable=False),
    sa.Column('normal_balance', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=True)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=True),
    sa.Column('agent_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_investigation_id'), 'agent_runs', ['investigation_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('before_state', sa.Text(), nullable=True),
    sa.Column('after_state', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('account_number_last4', sa.String(length=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('bank_account_id', sa.String(length=32), nullable=True),
    sa.Column('transaction_date', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('counterparty', sa.String(length=200), nullable=True),
    sa.Column('accounting_period', sa.String(length=7), nullable=False),
    sa.Column('matched_payment_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_accounting_period'), 'bank_transactions', ['accounting_period'], unique=False)
    op.create_table('credit_notes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('invoice_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('issued_date', sa.String(length=10), nullable=False),
    sa.Column('accounting_period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_notes_customer_id'), 'credit_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_invoice_id'), 'credit_notes', ['invoice_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('customer_tier', sa.String(length=20), nullable=False),
    sa.Column('payment_terms', sa.String(length=20), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('head_employee_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('discrepancy_ground_truth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('invoice_id', sa.String(length=32), nullable=False),
    sa.Column('expected_difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ground_truth_root_cause', sa.String(length=80), nullable=False),
    sa.Column('required_policy', sa.String(length=20), nullable=True),
    sa.Column('expected_action', sa.String(length=40), nullable=False),
    sa.Column('expected_resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrepancy_ground_truth_case_id'), 'discrepancy_ground_truth', ['case_id'], unique=True)
    op.create_index(op.f('ix_discrepancy_ground_truth_transaction_id'), 'discrepancy_ground_truth', ['transaction_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('invoice_id', sa.String(length=32), nullable=True),
    sa.Column('accounting_period', sa.String(length=7), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('vendor_id', sa.String(length=32), nullable=True),
    sa.Column('employee_id', sa.String(length=32), nullable=True),
    sa.Column('expense_date', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('account_code', sa.String(length=20), nullable=True),
    sa.Column('accounting_period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_accounting_period'), 'expenses', ['accounting_period'], unique=False)
    op.create_table('external_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('transaction_date', sa.String(length=10), nullable=False),
    sa.Column('tx_type', sa.String(length=40), nullable=False),
    sa.Column('customer', sa.String(length=160), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('invoice_id', sa.String(length=32), nullable=False),
    sa.Column('payment_id', sa.String(length=32), nullable=True),
    sa.Column('bank_transaction_id', sa.String(length=32), nullable=True),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('account_code', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discrepancy_type', sa.String(length=80), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transactions_customer_id'), 'financial_transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_period'), 'financial_transactions', ['period'], unique=False)
    op.create_index('ix_ft_period_status', 'financial_transactions', ['period', 'status'], unique=False)
    op.create_table('idempotent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('embedding_status', sa.String(length=20), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('journal_entry_id', sa.String(length=40), nullable=True),
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('accounting_period', sa.String(length=7), nullable=False),
    sa.Column('posted_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_account_code'), 'ledger_entries', ['account_code'], unique=False)
    op.create_index(op.f('ix_ledger_entries_accounting_period'), 'ledger_entries', ['accounting_period'], unique=False)
    op.create_index(op.f('ix_ledger_entries_journal_entry_id'), 'ledger_entries', ['journal_entry_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('policy_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_policy_id'), 'policies', ['policy_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('vendor_id', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('po_date', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('payment_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('refund_date', sa.String(length=10), nullable=False),
    sa.Column('accounting_period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_customer_id'), 'refunds', ['customer_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.String(length=40), nullable=True),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('arguments', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_agent_run_id'), 'tool_calls', ['agent_run_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_terms', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('adjustments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('journal_entry_id', sa.String(length=40), nullable=True),
    sa.Column('debit_account', sa.String(length=120), nullable=False),
    sa.Column('credit_account', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjustments_transaction_id'), 'adjustments', ['transaction_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approver_role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_transaction_id'), 'approval_requests', ['transaction_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_transaction_id'), 'approvals', ['transaction_id'], unique=False)
    op.create_table('discrepancies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('discrepancy_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('accounting_period', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrepancies_accounting_period'), 'discrepancies', ['accounting_period'], unique=False)
    op.create_index(op.f('ix_discrepancies_transaction_id'), 'discrepancies', ['transaction_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('timeline', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_transaction_id'), 'investigations', ['transaction_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('invoice_date', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.String(length=10), nullable=False),
    sa.Column('po_number', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accounting_period', sa.String(length=7), nullable=False),
    sa.Column('journal_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_accounting_period'), 'invoices', ['accounting_period'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=True),
    sa.Column('debit_account', sa.String(length=120), nullable=False),
    sa.Column('credit_account', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('accounting_period', sa.String(length=7), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_transaction_id'), 'journal_entries', ['transaction_id'], unique=False)
    op.create_table('manager_escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('escalated_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('slack_message_id', sa.String(length=80), nullable=True),
    sa.Column('slack_channel', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_escalations_transaction_id'), 'manager_escalations', ['transaction_id'], unique=False)
    op.create_table('monthly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_reports_period'), 'monthly_reports', ['period'], unique=True)
    op.create_table('payment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_requests_transaction_id'), 'payment_requests', ['transaction_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('invoice_id', sa.String(length=32), nullable=True),
    sa.Column('payment_date', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('bank_transaction_id', sa.String(length=32), nullable=True),
    sa.Column('accounting_period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_accounting_period'), 'payments', ['accounting_period'], unique=False)
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_table('revoked_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_sessions_token_id'), 'revoked_sessions', ['token_id'], unique=True)
    op.create_table('investigation_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('relevance', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('retrieval_method', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_evidence_investigation_id'), 'investigation_evidence', ['investigation_id'], unique=False)
    op.create_table('investigation_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.String(length=32), nullable=False),
    sa.Column('step_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_steps_investigation_id'), 'investigation_steps', ['investigation_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('account_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_investigation_steps_investigation_id'), table_name='investigation_steps')
    op.drop_table('investigation_steps')
    op.drop_index(op.f('ix_investigation_evidence_investigation_id'), table_name='investigation_evidence')
    op.drop_table('investigation_evidence')
    op.drop_index(op.f('ix_revoked_sessions_token_id'), table_name='revoked_sessions')
    op.drop_table('revoked_sessions')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_accounting_period'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_payment_requests_transaction_id'), table_name='payment_requests')
    op.drop_table('payment_requests')
    op.drop_index(op.f('ix_monthly_reports_period'), table_name='monthly_reports')
    op.drop_table('monthly_reports')
    op.drop_index(op.f('ix_manager_escalations_transaction_id'), table_name='manager_escalations')
    op.drop_table('manager_escalations')
    op.drop_index(op.f('ix_journal_entries_transaction_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_accounting_period'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_investigations_transaction_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_discrepancies_transaction_id'), table_name='discrepancies')
    op.drop_index(op.f('ix_discrepancies_accounting_period'), table_name='discrepancies')
    op.drop_table('discrepancies')
    op.drop_index(op.f('ix_approvals_transaction_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_approval_requests_transaction_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_adjustments_transaction_id'), table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tool_calls_agent_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_customer_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_policies_policy_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_table('organizations')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_ledger_entries_journal_entry_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_accounting_period'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account_code'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('knowledge_documents')
    op.drop_table('idempotent_actions')
    op.drop_index('ix_ft_period_status', table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_period'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_customer_id'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_table('external_integrations')
    op.drop_index(op.f('ix_expenses_accounting_period'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('employees')
    op.drop_table('documents')
    op.drop_index(op.f('ix_discrepancy_ground_truth_transaction_id'), table_name='discrepancy_ground_truth')
    op.drop_index(op.f('ix_discrepancy_ground_truth_case_id'), table_name='discrepancy_ground_truth')
    op.drop_table('discrepancy_ground_truth')
    op.drop_table('departments')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_credit_notes_invoice_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_customer_id'), table_name='credit_notes')
    op.drop_table('credit_notes')
    op.drop_index(op.f('ix_bank_transactions_accounting_period'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_table('bank_accounts')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_agent_runs_investigation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_accounting_periods_code'), table_name='accounting_periods')
    op.drop_table('accounting_periods')
    # ### end Alembic commands ###
