"""Updated id field in employees table

Revision ID: ecfe494a76d7
Revises: a7ea902d20c7
Create Date: 2026-09-21 14:04:08.600413
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecfe494a76d7'
down_revision: Union[str, None] = 'a7ea902d20c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
