"""Updated tables

Revision ID: fc8e0d4541a0
Revises: 5128a15b9f50
Create Date: 2026-09-21 13:44:18.511158
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8e0d4541a0'
down_revision: Union[str, None] = '5128a15b9f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('full_name', sa.String(length=160), nullable=False))
    op.add_column('employees', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('employees', sa.Column('role', sa.String(length=32), nullable=False))
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(length=160),
               nullable=True)
    op.alter_column('employees', 'department',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.alter_column('employees', 'department',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(length=160),
               nullable=False)
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.drop_column('employees', 'role')
    op.drop_column('employees', 'password_hash')
    op.drop_column('employees', 'full_name')
    # ### end Alembic commands ###
