"""Enumerations for financial close system."""
from __future__ import annotations

from enum import Enum


class Role(str, Enum):
    ADMIN = "ADMIN"
    FINANCE_ADMIN = "FINANCE_ADMIN"
    FINANCE_MANAGER = "FINANCE_MANAGER"
    ANALYST = "ANALYST"
    REGULAR_USER = "REGULAR_USER"


class PeriodStatus(str, Enum):
    OPEN = "OPEN"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"


class TransactionStatus(str, Enum):
    RECONCILED = "RECONCILED"
    DISCREPANCY_DETECTED = "DISCREPANCY_DETECTED"
    INVESTIGATING = "INVESTIGATING"
    AWAITING_HUMAN_APPROVAL = "AWAITING_HUMAN_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ESCALATED = "ESCALATED"
    AWAITING_MANAGER_APPROVAL = "AWAITING_MANAGER_APPROVAL"
    ADJUSTMENT_PENDING = "ADJUSTMENT_PENDING"
    ADJUSTED = "ADJUSTED"
    PAYMENT_REQUESTED = "PAYMENT_REQUESTED"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    RESOLVED = "RESOLVED"
    FAILED = "FAILED"
    REJECTED_MANAGER = "REJECTED_MANAGER"


class InvestigationStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ESCALATED = "ESCALATED"
    RESOLVED = "RESOLVED"
    FAILED = "FAILED"


class Severity(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class DocumentStatus(str, Enum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    EXTRACTING = "EXTRACTING"
    VALIDATING = "VALIDATING"
    NORMALIZED = "NORMALIZED"
    INDEXED = "INDEXED"
    FAILED = "FAILED"
